name = "Quagcraft"
author = "CurvedSwords"
version = "1.1.0"
description = "A Quagsire modpack"
pack-format = "packwiz:1.2.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab72f9c4b68c6aac2d767b880c20f707262a0b2b8c9d67e63ef2d78776552146"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
